env:
  browser: true
  es6: true
extends:
  - airbnb-base
  - eslint:recommended
  - plugin:prettier/recommended
  - plugin:vue/essential
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
  sourceType: module
  ecmaFeatures:
    jsx: true
plugins:
  - react
  - vue
rules: {}
